Adds ability to skip elements with special attribute 'assume-no-change'
nyxtom/reconcile.js pull request #6
Opened 2017-09-13 15:11 UTC by matthewma7

Hi @nyxtom, 

In our development, the need to skip certain element for comparison came up. 
This PR add an attribute to skip comparison for elements with the attribute **assume-no-change**.

Is this something we want to merge into the repo?

Sincerely,

2017-09-13 15:50 UTC, nyxtom commented
This seems fine but I might prefer something more generic like "ignore-changes"

2017-09-13 15:51 UTC, nyxtom commented
Actually assume-no-change is fine. Went back and forth on it but I actually like that better

2017-09-18 18:14 UTC, matthewma7 commented
@nyxtom, Thank you for your reply. Sorry that I missed your reply in the first place.
The initial PR is meant to give you a general idea. 
Is there something else needed for the PR to be merged? 
It will be great that once we can use the feature off npm.

2017-09-19 02:29 UTC, nyxtom requested changes

2017-09-19 02:29 UTC, nyxtom commented on reconcile.umd.js
> +            if (node.attributes && node.getAttribute('assume-no-change')===''){
Use hasAttribute instead. https://developer.mozilla.org/en-US/docs/Web/API/Element/hasAttribute

2017-09-19 02:29 UTC, nyxtom commented on reconcile.umd.js
> +            if (base.childNodes[i].attributes && base.childNodes[i].getAttribute('assume-no-change')===''){
Same here

2017-09-19 16:43 UTC, nyxtom approved these changes

2017-09-19 16:44 UTC, merged